/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import utils.FileUtils;

import javax.swing.SwingUtilities;

import org.bytedeco.javacpp.Loader;
import org.bytedeco.javacpp.opencv_objdetect;

/*
 * @author Thiago da Silva
 */
public class FrameCadastroDeFace extends javax.swing.JFrame {
    // GUI components

    private PanelCadastroDeFace panelVideo;
//  private PanelCadastroDeFace_superTreino panelVideo;


    public FrameCadastroDeFace() {
        super("Reconhecedor de Face");
        initComponents();
        this.setLocationRelativeTo(null);

//        conexao = new ConexaoDAO();
//        String ret = conexao.conectar("192.168.11.2", "controle_entrada", "root", "girafa1213");
//        if(ret.compareTo("true")!= 0){
//            Utilitarios.msg("Nao foi possivel conecar-se ao servidor 11.2 ( " + ret + " )");
//            return;
//        }
//        listaFuncionarios = new DaoFuncionario(conexao.getConexao()).consultaTodos();

        String property = System.getProperty("java.library.path");

        System.out.println("SISTEMA INICOU");
        System.out.println("PATH:::");
        System.out.println(property);

        // Preload the opencv_objdetect module to work around a known bug.
        Loader.load(opencv_objdetect.class);

        panelVideo = new PanelCadastroDeFace(this);
//        panelVideo = new PanelCadastroDeFace_superTreino(this);
        getContentPane().add(panelVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));
        pack();

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                panelVideo.closeDown();    // stop snapping pics
                System.exit(0);
            }
        });
    }


    public void setRecogName(final String faceName, final String dist)
    // update face name and its distance in the nameField; called from panel
    {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                fieldReconheceFace.setText(faceName + " (" + dist + ")");
            }
        });
    }  // end of setRecogName()


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        fieldNovaFace = new javax.swing.JTextField();
        btnSalvaFace = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fieldReconheceFace = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 680));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 441));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 12, 80));
        jPanel1.add(fieldNovaFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 166, -1));

        btnSalvaFace.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSalvaFace.setText("Treina a Face");
        btnSalvaFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaFaceActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvaFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel1.setText("Reconhecimento:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 140, 20));

        jLabel2.setText("Nova Face:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 20));

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 160, -1));

        fieldReconheceFace.setEditable(false);
        jPanel1.add(fieldReconheceFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 166, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 640, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvaFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaFaceActionPerformed
        fieldNovaFace.setEnabled(false);
        btnSalvaFace.setVisible(false);
        panelVideo.setSalvaFace(true);
    }//GEN-LAST:event_btnSalvaFaceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //cria nova thread para salvar novo facebundle no disco      
        ExecutorService salvaBundle = Executors.newSingleThreadScheduledExecutor();
        salvaBundle.execute(new Runnable() {
            @Override
            public void run() {
                panelVideo.setSalvaFace(true);//se nao der certo, adicionar bloco 'sincronized'
                long startTime = System.currentTimeMillis();
                FileUtils.salvarEigenSpace(panelVideo.getFaceRecog().getEigenSpace());
                System.out.println("BUNDLE SALVO EM " + (System.currentTimeMillis() - startTime) + "ms");
                panelVideo.setSalvaFace(false);
            }
        });

    }//GEN-LAST:event_jButton1ActionPerformed

    public String getNomeFaceField() {
        return String.valueOf(fieldNovaFace.getText());
    }

    public void setSalvarFaceVisible(boolean b) {
        btnSalvaFace.setVisible(b);
        fieldNovaFace.setEnabled(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new FrameCadastroDeFace().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvaFace;
    private javax.swing.JTextField fieldNovaFace;
    private javax.swing.JTextField fieldReconheceFace;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
